/// Flutter icons MyPgmIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyPgmIcons
///      fonts:
///       - asset: fonts/MyPgmIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyPgmIcons {
  MyPgmIcons._();

  static const _kFontFam = 'MyPgmIcons';
  static const _kFontPkg = null;

  static const IconData c_plain = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cplusplus_plain = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heroku_plain = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rails_plain = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ruby_plain = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData typescript_plain = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
